spring.datasource.url=jdbc:mysql://root:qMDkxRkxVTXFqtRHhMkkuBmLrIEPDNuu@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=qMDkxRkxVTXFqtRHhMkkuBmLrIEPDNuu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hotelroyalblue2026@gmail.com
spring.mail.password=nwxc hkkr fnhg rgik 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

